name: Move Trello Card When Pull Request Created

on:
  pull_request:
    types: [opened]
    branches: [ "main" ]

jobs:
  link_with_trello:
    name: Move Trello Card
    runs-on: ubuntu-latest
    steps:
    - name: Call trello-github-actions 
      id: call-trello-github-actions
      uses: Grabtot/trello-github-actions@v1.3 
      with:
        trello-action: move_card_when_pull_request_opened
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        TRELLO_TODO_LIST_ID: ${{ secrets.TRELLO_TODO_LIST_ID }}
        TRELLO_IN_PROGRESS_LIST_ID: ${{ secrets.TRELLO_IN_PROGRESS_LIST_ID }}
        TRELLO_DEBUGING_LIST_ID: ${{ secrets.TRELLO_DEBUGING_LIST_ID }}
        TRELLO_DONE_LIST_ID: ${{ secrets.TRELLO_DONE_LIST_ID }}
